name: YAML Linter
on:
  pull_request:
    paths: ['**/*.yaml', '**/*.yml']

permissions:
  contents: read    

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ibiqlik/action-yamllint@v3
      with:
        config_data: |
          extends: default
          ignore: |
            examples/linting.yml
            .github/workflows/**/*
          rules:
            document-start: disable
            new-line-at-end-of-file: disable
            truthy: disable
            line-length: disable
            empty-lines:
              level: warning
            trailing-spaces:
              level: warning
